apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext: 
        runAsUser: 0 
        runAsGroup: 0 
        fsGroup: 0 
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
            # - name: docker-daemon-volume
            #   mountPath: /var/run/docker.sock

      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: my-pvc

        # - name: docker-daemon-volume
        #   hostPath:
        #     path: /var/run/docker.sock